#Para definiir el nombre de la aplicaciojn
spring.application.name= Tienda
#definir el puerto de red que  escucha la aplicacion de manera web
server.port= 80

#Definimos el formato de fecha y hora en el login
logging.pattern.dateformat=hh:mm

spring.main.banner-mode=false

#En desarrollo el cache del servidor debe estar en false, en produccion debe estar en true
spring.thymeleaf.cache=false
